name: loomi_challenge
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  cached_network_image: ^3.0.0
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/home_card_nba_placeholder.png
    - assets/images/home_card_league_of_legends.png
    - assets/images/home_card_popular_tournaments.png
    - assets/images/basketball_icon.png
    - assets/images/soccer_icon.png
    - assets/images/whistle_icon.png
    - assets/images/eesports_icon.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
